exports.authRoute = require('./authRoute');
exports.vendorRoute = require('./vendorRoute');
exports.uploadRoute = require('./uploadRoute');
exports.userRoute = require('./userRoute');
exports.kycRoute = require('./kycRoute');
exports.planRoute = require('./planRoute');
exports.subcriptionRoute = require('./subcriptionRoute');
exports.listingRoute = require('./listingRoute');
exports.amenityRoute = require('./amenityRoute');
exports.gadgetRoute = require('./gadgetRoute');
exports.categoryRoute = require('./categoryRoute');
exports.faqRoute = require('./faqRoute');
exports.requestRoute=require("./requestRoute");
exports.disputeRoute=require("./disputeRoute")
exports.accountRoute=require("./accountRoute")
exports.textForumRoute=require("./taxForumRoute")
exports.reviewRoute = require('./reviewRoute');
exports.reportReviewRoute = require('./reportReviewRoute');
exports.advertisementRoute = require('./advertisementRoute');
exports.templeteRoute = require('./templeteRoute');
exports.subAdminRoute = require('./AdminRoute');
exports.cityRoute = require('./cityRoute');
exports.countryRoute = require('./countryRoute');
exports.logsRoute = require('./LogsRoute');
exports.discountRoute = require('./discountRoute')
exports.settingRoute = require('./settingRoute');
exports.payoutRoute = require('./payoutRoute');
exports.topicRoute = require('./topicRoute');
exports.calendarRoute = require('./calendarRoute');
exports.paymentRoute = require('./paymentRoute');
exports.reportRoute = require('./reportRoute');
exports.staffRoute= require("./staffRoute")
exports.newsLetterRoute = require('./newsLetterRoute');
exports.filterRoute=require("./filterRoute")
exports.messageRoute = require('./messageRoute');
exports.supportRoute = require('./supportRoute');
exports.eventTypeRoute = require('./eventTypeRoute');
exports.clientReviewRoute = require('./clientReviewRoute');
exports.alertRoute = require('./alertRoute');
exports.suspensionRoute = require('./suspensionRoute');
exports.chatViolationRoute = require('./chatViolationRoute');
exports.adminNoteRoute = require('./adminNoteRoute');
exports.venueDetectionRoute = require('./venueDetectionRoute');
exports.sharedCartPaymentRoute = require('./sharedCartPaymentRoute');